### ISSUE TITLE
Update readme for new python3 pip

### ISSUE THREAD

**Issue by vazome** [XaviTorello/mail2gg#8]
`pip install mail2gg` will not work if you have python3.
You should use `pip3 install mail2gg` instead.

**Comment by XaviTorello** [comment]
`pip3` binary is normally linked as `pip` at OS/virtualenv level.

I think it takes no sense to enforce and hardcode the version on the binary version, but if you think that this can be problematic you could raise a PR extending the README :)

**Comment by vazome** [comment]
@XaviTorello  Basically I mean that average user will download the latest python, which is 3. On this version of Python, the pip will not respond to `pip`. It will respond only to `pip3` (tested on macOS). The softlink is not setup.

So I am suggesting to edit README because python3 is mostly used which has 'pip3' option by default.
